### ISSUE TITLE
brew services - Unknown command: services

### ISSUE THREAD

**Issue by dr1s** [Homebrew/homebrew-services#206]
The latest [commit](https://github.com/Homebrew/homebrew-services/commit/693e4bbf06b0bef91bd65d3c3b57af6ce59c0388) breaks `brew services` for me.

Reverting `/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services` to this [commit](https://github.com/Homebrew/homebrew-services/tree/fbfa39a451f33d8960ee94c6e48b167016a1d5aa) made it work again,

**Comment by LioraLevy** [comment]
same issue for me

**Comment by MikeMcQuaid** [comment]
What is your `brew config` output?

**Comment by MikeMcQuaid** [comment]
Run `brew update` this is now fixed by a new Homebrew/brew tag.

**Comment by LYJSPEEDX** [comment]
This error still occurred on Macos 10.15.3.
I have untap the homebrew/services repository and retap it, and then what shown in console proved the existence of issue.
I have update homebrew to lastest version.
<img width="724" alt="service" src="https://user-images.githubusercontent.com/26499797/73998922-07a2ed80-499e-11ea-9322-7ebdbf42945f.png">

**Comment by MikeMcQuaid** [comment]
@LYJSPEEDX You need to `brew update`. If that's not working: post your `brew config` here.

**Comment by LYJSPEEDX** [comment]
I have updated brew. Proved to be not working.
![image](https://user-images.githubusercontent.com/26499797/74077972-bb1fe680-4a5f-11ea-91af-b5b92b88c01a.png)

**Comment by MikeMcQuaid** [comment]
@LYJSPEEDX Run `brew update-reset`, there's something wrong with your Homebrew. "Last commit: 6 months ago" should have been a clue.

**Comment by hitao123** [comment]
same issue for me

**Comment by LYJSPEEDX** [comment]
@MikeMcQuaid It works! My gratitude is beyond expression, thank U!
